spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  liquibase:
    enabled: false
  main:
    banner-mode: off

app:
  cors:
    allowed-origins: http://localhost:3000
  security:
    jwt-issuer: atendepro-test
    jwt-secret: teste-local-sem-valor-real
    jwt-expiracao-minutos: 60
    jwt-refresh-expiracao-dias: 7
